version : '3'

services :
  api :
    build :
      context : .
      dockerfile : Dockerfile
    environment :
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: test_user
      DB_PASSWORD: test1234
      DB_DATABASE: 
    ports :
      - "80:80"

    depends_on :
      mysql :
        condition : service_healthy
    links :
      - mysql
    command : ["sh", "./run.sh"]



  mysql :
    image : mysql
    ports:
      - "3306:3306"
    environment :
      MYSQL_ROOT_PASSWORD : password1234
      MYSQL_DATABASE: dashboard
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test1234

    healthcheck:
      test : ["CMD", "mysqladmin", "ping", "-h", "localhost"]