version : '3'

services :
  api :
    build :
      context : .
      dockerfile : Dockerfile
    environment :
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: test_user
      DB_PASSWORD: test1234
      DB_DATABASE: 
    ports :
      - "8000:8000"

    depends_on :
      mysql :
        condition : service_healthy

    healthcheck:
      test : ["CMD", "curl", "-X", "GET", "http://localhost:8000/ping"]
      timeout : 5s
      retries : 1
      
    networks : 
      - my_network
    command : ["sh", "./run.sh"]
    



  mysql :
    image : mysql
    ports:
      - "3306:3306"
    environment :
      MYSQL_ROOT_PASSWORD : password1234
      MYSQL_DATABASE: dashboard
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test1234
    healthcheck:
      test : ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    networks : 
      - my_network


  nginx :
    build : ./nginx
    volumes :
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on :
      api :
        condition : service_healthy
    networks : 
      - my_network


networks :
  my_network :